language: node_js
env: CI=true
sudo: false

before_install:
  - npm install --global grunt-cli

node_js:
  - "iojs"
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs-v1.0"
  - "iojs-v1.1"
  - "iojs-v1.2"
  - "iojs-v1.3"
  - "iojs-v1.4"
  - "iojs-v1.5"
  - "iojs-v1.6"
  - "iojs"

notifications:
  email:
    - qiuzhongleiabc@126.com

